---
deployment:
  tasks:
    - export DEPLOYPATH=/home/barkgjug/public_html/
    - rsync -a --exclude='.git' --exclude='.gitignore' --exclude='.cpanel.yml' --exclude='error_log' --exclude='design_handoff_barkly_redesign 2' . $DEPLOYPATH
